/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "libs.h"
#include "led.h"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


extern void initialise_monitor_handles(void);  //to initialize semi-hosting features


int main(void)
{
	//uint32_t volatile * const SHCSR = (uint32_t*)0xE000ED24;  //register for enabling systick timer exception
	//*SHCSR |= (1 << 11);  //enable systick timer exception

	enable_processor_faults();
	
	initialise_monitor_handles();

	init_scheduler_stack(SCHED_STACK_START);
	
	printf("inside Main() of task scheduler program\n");

	init_tasks_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

	/* Loop forever */
	for(;;);
}

